import { INITIAL_ICON_STATE, type IconState } from "../types";

export type IconPreset = {
  id: string;
  label: string;
  description: string;
  family: string;
  archetype: string;
  variant: string;
  size: string;
  tags?: string[];
  state: Partial<IconState>;
};

const buildPreset = (
  id: string,
  label: string,
  description: string,
  family: string,
  archetype: string,
  variant: string,
  size: string,
  tags: string[],
  state: Partial<IconState>,
): IconPreset => ({
  id,
  label,
  description,
  family,
  archetype,
  variant,
  size,
  tags,
  state: {
    ...INITIAL_ICON_STATE,
    ...state,
  },
});

const BASE_ICON_PRESETS: IconPreset[] = [
  buildPreset(
    "glass-glyph",
    "Glass Glyph",
    "Translucent icon container with soft blur and refined shadow.",
    "signature",
    "glass",
    "glyph",
    "md",
    ["glass", "container", "glyph", "soft"],
    {
      shape: "rounded",
      containerColor: "rgba(255,255,255,0.22)",
      containerOpacity: 0.88,
      glassBlur: 18,
      shadowEnabled: true,
      shadowColor: "rgba(15,23,42,0.16)",
      shadowBlur: 18,
      reflectionEnabled: true,
      hoverEffect: "glow",
      entranceAnimation: "fade",
      ariaLabel: "Glass glyph icon",
    },
  ),
  buildPreset(
    "neon-orb",
    "Neon Orb",
    "Glowing circular icon with gradient stroke and motion.",
    "signature",
    "neon",
    "orb",
    "md",
    ["neon", "orb", "gradient", "glow"],
    {
      shape: "circle",
      containerColor: "#020617",
      containerOpacity: 0.92,
      gradientEnabled: true,
      gradientStart: "#22d3ee",
      gradientEnd: "#a855f7",
      glowEnabled: true,
      glowColor: "#22d3ee",
      glowBlur: 18,
      shadowEnabled: true,
      shadowColor: "rgba(34,211,238,0.35)",
      shadowBlur: 24,
      animationType: "pulse",
      animationDuration: 1400,
      hoverEffect: "scale",
      entranceAnimation: "zoom",
      ariaLabel: "Neon orb icon",
    },
  ),
  buildPreset(
    "editorial-monoline",
    "Editorial Monoline",
    "Minimal container with serif-like balance and subtle border.",
    "signature",
    "editorial",
    "monoline",
    "md",
    ["editorial", "minimal", "border", "monoline"],
    {
      shape: "rounded",
      containerColor: "#ffffff",
      containerOpacity: 1,
      borderWidth: 1,
      borderColor: "#cbd5e1",
      borderStyle: "solid",
      shadowEnabled: true,
      shadowColor: "rgba(15,23,42,0.08)",
      shadowBlur: 10,
      glowEnabled: false,
      reflectionEnabled: false,
      hoverEffect: "none",
      entranceAnimation: "slide-up",
      ariaLabel: "Editorial monoline icon",
    },
  ),
  buildPreset(
    "3d-ribbon",
    "3D Ribbon",
    "Perspective-driven icon with strong depth and movement.",
    "signature",
    "3d",
    "ribbon",
    "md",
    ["3d", "depth", "motion", "premium"],
    {
      use3D: true,
      rotateX: 14,
      rotateY: -18,
      rotateZ: 4,
      depth: 36,
      perspective: 1200,
      shape: "squircle",
      containerColor: "#0f172a",
      containerOpacity: 0.9,
      shadowEnabled: true,
      shadowColor: "rgba(15,23,42,0.22)",
      shadowBlur: 24,
      animationType: "float",
      animationDuration: 2200,
      hoverEffect: "3d-tilt",
      entranceAnimation: "rotate-in",
      ariaLabel: "3D ribbon icon",
    },
  ),
  buildPreset(
    "badge-solid",
    "Badge Solid",
    "Strong icon badge with solid fill and a compact container.",
    "signature",
    "badge",
    "solid",
    "sm",
    ["badge", "solid", "compact", "brand"],
    {
      shape: "circle",
      containerSize: 72,
      containerPadding: 14,
      containerColor: "#eff6ff",
      containerOpacity: 1,
      borderWidth: 0,
      fillColor: "#3b82f6",
      fillOpacity: 0.12,
      glowEnabled: false,
      shadowEnabled: true,
      shadowColor: "rgba(59,130,246,0.18)",
      shadowBlur: 14,
      hoverEffect: "fill",
      entranceAnimation: "fade",
      ariaLabel: "Badge solid icon",
    },
  ),
  buildPreset(
    "motion-sweep",
    "Motion Sweep",
    "Animated icon with lift, spin, and hover energy.",
    "signature",
    "motion",
    "sweep",
    "md",
    ["motion", "animated", "sweep", "energy"],
    {
      iconName: "Sparkles",
      animationType: "spin",
      animationDuration: 2600,
      animationRepeat: true,
      glowEnabled: true,
      glowColor: "#f472b6",
      glowBlur: 12,
      hoverEffect: "rotate",
      entranceAnimation: "fade",
      ariaLabel: "Motion sweep icon",
    },
  ),
  buildPreset(
    "chrome-chip",
    "Chrome Chip",
    "Silver-toned icon chip with sheen, border, and quiet depth.",
    "signature",
    "chrome",
    "chip",
    "md",
    ["chrome", "chip", "metal", "sheen"],
    {
      shape: "rounded",
      containerColor: "#f8fafc",
      containerOpacity: 1,
      borderWidth: 1,
      borderColor: "#cbd5e1",
      borderStyle: "solid",
      shadowEnabled: true,
      shadowColor: "rgba(15,23,42,0.12)",
      shadowBlur: 16,
      reflectionEnabled: true,
      hoverEffect: "glow",
      entranceAnimation: "fade",
      ariaLabel: "Chrome chip icon",
    },
  ),
  buildPreset(
    "halo-card",
    "Halo Card",
    "Container-heavy icon preset with neon halo and glass blur.",
    "signature",
    "halo",
    "card",
    "lg",
    ["halo", "glass", "card", "neon"],
    {
      shape: "square",
      containerSize: 84,
      containerPadding: 18,
      containerColor: "rgba(15,23,42,0.86)",
      containerOpacity: 0.94,
      glassBlur: 14,
      glowEnabled: true,
      glowColor: "#38bdf8",
      glowBlur: 16,
      shadowEnabled: true,
      shadowColor: "rgba(56,189,248,0.28)",
      shadowBlur: 22,
      gradientEnabled: true,
      gradientStart: "#0ea5e9",
      gradientEnd: "#8b5cf6",
      hoverEffect: "scale",
      entranceAnimation: "zoom",
      ariaLabel: "Halo card icon",
    },
  ),
  buildPreset(
    "outline-emblem",
    "Outline Emblem",
    "High-contrast outlined icon container with clean geometry.",
    "signature",
    "outline",
    "emblem",
    "md",
    ["outline", "emblem", "geometric", "clean"],
    {
      shape: "square",
      containerColor: "#ffffff",
      containerOpacity: 1,
      borderWidth: 2,
      borderColor: "#475569",
      borderStyle: "dashed",
      shadowEnabled: false,
      hoverEffect: "none",
      entranceAnimation: "none",
      ariaLabel: "Outline emblem icon",
    },
  ),
  buildPreset(
    "glass-dashboard",
    "Glass Dashboard",
    "Dashboard-like container with glass blur and subtle fill emphasis.",
    "signature",
    "glass",
    "dashboard",
    "lg",
    ["dashboard", "glass", "product", "soft"],
    {
      shape: "rounded",
      containerSize: 96,
      containerPadding: 20,
      containerColor: "rgba(255,255,255,0.26)",
      containerOpacity: 0.9,
      glassBlur: 20,
      shadowEnabled: true,
      shadowColor: "rgba(15,23,42,0.18)",
      shadowBlur: 20,
      reflectionEnabled: true,
      hoverEffect: "scale",
      entranceAnimation: "fade",
      ariaLabel: "Glass dashboard icon",
    },
  ),
  buildPreset(
    "mono-keyline",
    "Mono Keyline",
    "Quiet mono icon treatment with a precise border and restrained motion.",
    "signature",
    "mono",
    "keyline",
    "md",
    ["mono", "keyline", "quiet", "editorial"],
    {
      shape: "none",
      containerColor: "#ffffff",
      containerOpacity: 1,
      borderWidth: 1,
      borderColor: "#e2e8f0",
      shadowEnabled: false,
      glowEnabled: false,
      hoverEffect: "none",
      entranceAnimation: "slide-up",
      ariaLabel: "Mono keyline icon",
    },
  ),
  buildPreset(
    "vivid-launch",
    "Vivid Launch",
    "Bold launch icon with saturated gradient and punchy hover motion.",
    "signature",
    "launch",
    "vivid",
    "lg",
    ["launch", "vivid", "gradient", "cta"],
    {
      shape: "circle",
      containerColor: "#111827",
      containerOpacity: 1,
      gradientEnabled: true,
      gradientStart: "#f97316",
      gradientEnd: "#ec4899",
      glowEnabled: true,
      glowColor: "#fb7185",
      glowBlur: 20,
      shadowEnabled: true,
      shadowColor: "rgba(236,72,153,0.32)",
      shadowBlur: 24,
      animationType: "bounce",
      animationDuration: 1800,
      hoverEffect: "scale",
      entranceAnimation: "zoom",
      ariaLabel: "Vivid launch icon",
    },
  ),
];

type IconTheme = {
  id: string;
  label: string;
  accent: string;
  accent2: string;
  container: string;
  border: string;
  shadow: string;
};

type IconArchetype = {
  id: string;
  label: string;
  description: string;
  tags: string[];
  shape: IconState["shape"];
  hoverEffect: IconState["hoverEffect"];
  entranceAnimation: IconState["entranceAnimation"];
  animationType: IconState["animationType"];
  gradientEnabled: boolean;
  use3D: boolean;
  glowEnabled: boolean;
  reflectionEnabled: boolean;
  neumorphic: boolean;
};

const THEMES: IconTheme[] = [
  { id: "slate", label: "Slate", accent: "#64748b", accent2: "#cbd5e1", container: "#ffffff", border: "#e2e8f0", shadow: "rgba(15,23,42,0.14)" },
  { id: "cobalt", label: "Cobalt", accent: "#3b82f6", accent2: "#93c5fd", container: "#dbeafe", border: "#93c5fd", shadow: "rgba(59,130,246,0.25)" },
  { id: "emerald", label: "Emerald", accent: "#10b981", accent2: "#6ee7b7", container: "#d1fae5", border: "#6ee7b7", shadow: "rgba(16,185,129,0.24)" },
  { id: "sunset", label: "Sunset", accent: "#f97316", accent2: "#fdba74", container: "#ffedd5", border: "#fdba74", shadow: "rgba(249,115,22,0.24)" },
  { id: "rose", label: "Rose", accent: "#f43f5e", accent2: "#fda4af", container: "#ffe4e6", border: "#fda4af", shadow: "rgba(244,63,94,0.24)" },
  { id: "violet", label: "Violet", accent: "#8b5cf6", accent2: "#c4b5fd", container: "#ede9fe", border: "#c4b5fd", shadow: "rgba(139,92,246,0.24)" },
  { id: "amber", label: "Amber", accent: "#f59e0b", accent2: "#fcd34d", container: "#fef3c7", border: "#fcd34d", shadow: "rgba(245,158,11,0.25)" },
  { id: "mint", label: "Mint", accent: "#14b8a6", accent2: "#99f6e4", container: "#ccfbf1", border: "#5eead4", shadow: "rgba(20,184,166,0.24)" },
  { id: "arctic", label: "Arctic", accent: "#38bdf8", accent2: "#bae6fd", container: "#e0f2fe", border: "#7dd3fc", shadow: "rgba(56,189,248,0.24)" },
  { id: "cherry", label: "Cherry", accent: "#e11d48", accent2: "#fb7185", container: "#ffe4e6", border: "#fb7185", shadow: "rgba(225,29,72,0.26)" },
  { id: "obsidian", label: "Obsidian", accent: "#94a3b8", accent2: "#cbd5e1", container: "#0f172a", border: "#334155", shadow: "rgba(15,23,42,0.4)" },
  { id: "indigo", label: "Indigo", accent: "#6366f1", accent2: "#a5b4fc", container: "#e0e7ff", border: "#a5b4fc", shadow: "rgba(99,102,241,0.24)" },
];

const ARCHETYPES: IconArchetype[] = [
  { id: "glass-glyph", label: "Glass Glyph", description: "Soft translucent icon chip with polished blur.", tags: ["glass", "chip", "soft", "product"], shape: "rounded", hoverEffect: "glow", entranceAnimation: "fade", animationType: "none", gradientEnabled: false, use3D: false, glowEnabled: false, reflectionEnabled: true, neumorphic: false },
  { id: "neon-orb", label: "Neon Orb", description: "Orb-like icon with glow-heavy nightlife energy.", tags: ["neon", "orb", "glow", "gradient"], shape: "circle", hoverEffect: "scale", entranceAnimation: "zoom", animationType: "pulse", gradientEnabled: true, use3D: false, glowEnabled: true, reflectionEnabled: false, neumorphic: false },
  { id: "editorial-monoline", label: "Editorial Monoline", description: "Restrained mono icon for editorial surfaces.", tags: ["editorial", "minimal", "monoline", "quiet"], shape: "none", hoverEffect: "none", entranceAnimation: "slide-up", animationType: "none", gradientEnabled: false, use3D: false, glowEnabled: false, reflectionEnabled: false, neumorphic: false },
  { id: "ribbon-3d", label: "Ribbon 3D", description: "Depth-driven icon with perspective and motion.", tags: ["3d", "depth", "motion", "premium"], shape: "squircle", hoverEffect: "3d-tilt", entranceAnimation: "rotate-in", animationType: "float", gradientEnabled: true, use3D: true, glowEnabled: false, reflectionEnabled: false, neumorphic: false },
  { id: "badge-solid", label: "Badge Solid", description: "Compact badge icon with strong presence.", tags: ["badge", "solid", "brand", "compact"], shape: "circle", hoverEffect: "fill", entranceAnimation: "fade", animationType: "none", gradientEnabled: false, use3D: false, glowEnabled: false, reflectionEnabled: false, neumorphic: false },
  { id: "motion-sweep", label: "Motion Sweep", description: "Lively launch icon with animated energy.", tags: ["motion", "animated", "launch", "energy"], shape: "rounded", hoverEffect: "rotate", entranceAnimation: "fade", animationType: "spin", gradientEnabled: true, use3D: false, glowEnabled: true, reflectionEnabled: false, neumorphic: false },
  { id: "chrome-chip", label: "Chrome Chip", description: "Reflective chip with metallic polish.", tags: ["chrome", "metal", "chip", "reflective"], shape: "rounded", hoverEffect: "glow", entranceAnimation: "fade", animationType: "none", gradientEnabled: false, use3D: false, glowEnabled: false, reflectionEnabled: true, neumorphic: false },
  { id: "halo-card", label: "Halo Card", description: "Container-heavy card preset with halo lighting.", tags: ["halo", "card", "glass", "premium"], shape: "square", hoverEffect: "scale", entranceAnimation: "zoom", animationType: "pulse", gradientEnabled: true, use3D: false, glowEnabled: true, reflectionEnabled: true, neumorphic: false },
  { id: "outline-emblem", label: "Outline Emblem", description: "Geometry-first outline container for product marks.", tags: ["outline", "emblem", "geometry", "clean"], shape: "square", hoverEffect: "none", entranceAnimation: "none", animationType: "none", gradientEnabled: false, use3D: false, glowEnabled: false, reflectionEnabled: false, neumorphic: false },
  { id: "glass-dashboard", label: "Glass Dashboard", description: "Glass dashboard chip with ambient depth.", tags: ["dashboard", "glass", "soft", "product"], shape: "rounded", hoverEffect: "scale", entranceAnimation: "fade", animationType: "none", gradientEnabled: false, use3D: false, glowEnabled: false, reflectionEnabled: true, neumorphic: false },
  { id: "mono-keyline", label: "Mono Keyline", description: "Ultra-quiet mono glyph with keyline framing.", tags: ["mono", "keyline", "quiet", "editorial"], shape: "none", hoverEffect: "none", entranceAnimation: "slide-up", animationType: "none", gradientEnabled: false, use3D: false, glowEnabled: false, reflectionEnabled: false, neumorphic: false },
  { id: "neumorph-emblem", label: "Neumorph Emblem", description: "Convex product icon with embossed depth.", tags: ["neumorph", "embossed", "soft", "utility"], shape: "rounded", hoverEffect: "scale", entranceAnimation: "fade", animationType: "bounce", gradientEnabled: false, use3D: false, glowEnabled: false, reflectionEnabled: false, neumorphic: true },
];

const SIZE_PROFILES = [
  { id: "xs", label: "Compact", size: 24, containerSize: 52, padding: 12 },
  { id: "sm", label: "Balanced", size: 32, containerSize: 64, padding: 14 },
  { id: "md", label: "Studio", size: 40, containerSize: 76, padding: 16 },
  { id: "lg", label: "Hero", size: 52, containerSize: 92, padding: 20 },
];

function buildGeneratedPreset(
  theme: IconTheme,
  archetype: IconArchetype,
  size: (typeof SIZE_PROFILES)[number],
): IconPreset {
  return {
    id: `${theme.id}-${archetype.id}-${size.id}`,
    label: `${theme.label} ${archetype.label} ${size.label}`,
    description: `${archetype.description} Tuned with the ${theme.label.toLowerCase()} family and ${size.label.toLowerCase()} scale.`,
    family: theme.id,
    archetype: archetype.id,
    variant: archetype.label,
    size: size.id,
    tags: [theme.id, archetype.id, size.id, ...archetype.tags],
    state: {
      ...INITIAL_ICON_STATE,
      iconName: archetype.id === "motion-sweep" ? "Sparkles" : archetype.id === "outline-emblem" ? "Shield" : "Activity",
      size: size.size,
      strokeWidth: size.id === "xs" ? 1.8 : size.id === "lg" ? 2.6 : 2.2,
      color: theme.accent,
      fillColor: theme.accent,
      fillOpacity: archetype.hoverEffect === "fill" ? 0.14 : 0,
      gradientEnabled: archetype.gradientEnabled,
      gradientStart: theme.accent,
      gradientEnd: theme.accent2,
      shape: archetype.shape,
      containerSize: size.containerSize,
      containerPadding: size.padding,
      containerColor: theme.container,
      containerOpacity: theme.id === "obsidian" ? 0.92 : archetype.id.includes("glass") ? 0.88 : 1,
      borderWidth: archetype.shape === "none" ? 0 : archetype.id === "outline-emblem" ? 2 : 1,
      borderColor: theme.border,
      borderStyle: archetype.id === "outline-emblem" ? "dashed" : "solid",
      borderRadius: archetype.shape === "rounded" ? 18 : archetype.shape === "squircle" ? 24 : 12,
      glassBlur: archetype.id.includes("glass") ? 18 : 0,
      glassOpacity: archetype.id.includes("glass") ? 0.22 : 0,
      neumorphic: archetype.neumorphic,
      neumorphicElevation: archetype.neumorphic ? "convex" : "flat",
      shadowEnabled: archetype.shape !== "none",
      shadowColor: theme.shadow,
      shadowBlur: size.id === "lg" ? 24 : 18,
      glowEnabled: archetype.glowEnabled,
      glowColor: theme.accent,
      glowBlur: size.id === "lg" ? 20 : 14,
      reflectionEnabled: archetype.reflectionEnabled,
      use3D: archetype.use3D,
      rotateX: archetype.use3D ? 12 : 0,
      rotateY: archetype.use3D ? -16 : 0,
      rotateZ: archetype.use3D ? 4 : 0,
      depth: archetype.use3D ? 28 : 10,
      perspective: archetype.use3D ? 1200 : 1000,
      animationType: archetype.animationType,
      animationDuration: archetype.animationType === "none" ? 1 : size.id === "lg" ? 2.2 : 1.6,
      animationRepeat: true,
      hoverEffect: archetype.hoverEffect,
      entranceAnimation: archetype.entranceAnimation,
      ariaLabel: `${theme.label} ${archetype.label} icon`,
      ariaRole: "img",
      ariaHidden: false,
    },
  };
}

const GENERATED_ICON_PRESETS: IconPreset[] = THEMES.flatMap((theme) =>
  ARCHETYPES.flatMap((archetype) =>
    SIZE_PROFILES.map((size) => buildGeneratedPreset(theme, archetype, size)),
  ),
);

export const ICON_PRESETS: IconPreset[] = [
  ...BASE_ICON_PRESETS,
  ...GENERATED_ICON_PRESETS,
];
